# CodeRabbit Configuration for ppanayotov-com
# https://docs.coderabbit.ai/guides/configure-coderabbit

# Language and frameworks
language: en-US
early_access: false
enable_free_tier: true

# Review settings
reviews:
  profile: chill
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords:
      - "WIP"
      - "DO NOT REVIEW"
      - "DRAFT"

  # Tools and languages to review
  tools:
    github-checks:
      enabled: true
      timeout: 90

  # Path-based review configuration
  path_filters:
    - "!**/node_modules/**"
    - "!**/.next/**"
    - "!**/dist/**"
    - "!**/build/**"
    - "!**/*.min.js"
    - "!**/package-lock.json"
    - "!**/pnpm-lock.yaml"

# Chat settings
chat:
  auto_reply: true

# Knowledge base
knowledge_base:
  # Learnings from project structure
  learnings:
    - "This is a Next.js 15 App Router project with TypeScript"
    - "Data is stored in static TypeScript files in /data/ directory (no database)"
    - "Admin panel should NOT be deployed to production unless secured"
    - "Blog uses markdown files stored in /data/blog/"
    - "Images are optimized using Sharp library"
    - "Contact information must remain non-clickable for bot protection"
    - "Print functionality has been completely removed"
    - "Uses Incremental Static Regeneration (ISR) for blog pages"

  # Custom instructions for reviews
  custom_instructions:
    - "Check for security issues in admin routes and API endpoints"
    - "Verify that contact information remains non-clickable (no mailto: or tel: links)"
    - "Ensure proper TypeScript types and avoid 'any' where possible"
    - "Check for accessibility (ARIA labels, semantic HTML, keyboard navigation)"
    - "Verify Next.js 15 best practices (Server Components, async metadata, etc.)"
    - "Check for performance issues (large bundle sizes, unnecessary re-renders)"
    - "Ensure proper error handling in async operations"
    - "Verify that admin panel changes don't affect public-facing pages"
    - "Check for proper ISR/SSG configuration on blog pages"
    - "Ensure all data comes from /data/ files, not hardcoded values"

# Review focus areas
focus_areas:
  - security
  - performance
  - accessibility
  - best_practices
  - type_safety

# Disable certain review types
disable:
  - "nitpick_comments"
