import { OpenRouterOptions } from "../types/index";
import { env } from "@/lib/env";
import { logger } from "@/lib/logger";

/**
 * Requests a single answer from the OpenRouter language model API using the provided system prompt and user input.
 *
 * @param options - Contains the system prompt, user input, and optional creativity level for the model's response.
 * @returns The trimmed answer string generated by the model, or an empty string if no answer is returned.
 *
 * @throws {Error} If the `OPENROUTER_KEY` environment variable is not set or if the OpenRouter API responds with an error.
 */
export async function getOpenRouterAnswer({
  systemInput,
  data,
  creativity = 0.2,
  signal,
  customModel
}: OpenRouterOptions): Promise<string> {
  // Validate that systemInput and data are not empty
  if (!systemInput || systemInput.trim() === "") {
    throw new Error("System input cannot be empty");
  }

  if (!data || data.trim() === "") {
    throw new Error("User data cannot be empty");
  }

  const apiKey = env.OPENROUTER_KEY;
  // Use customModel if provided, otherwise fall back to env variable
  const model = customModel || env.OPENROUTER_MODEL;

  const response = await fetch(
    "https://openrouter.ai/api/v1/chat/completions",
    {
      method: "POST",
      headers: {
        Authorization: `Bearer ${apiKey}`,
        "Content-Type": "application/json"
      },
      // Add signal for timeout handling if provided
      ...(signal && { signal }),
      body: JSON.stringify({
        model,
        messages: [
          { role: "system", content: systemInput },
          { role: "user", content: data }
        ],
        max_tokens: 512,
        temperature: creativity,
        n: 1
      })
    }
  );

  if (!response.ok) {
    const error = await response.text();
    logger.error('OpenRouter API request failed', new Error(`OpenRouter API error: ${error}`), {
      model,
      status: response.status,
      statusText: response.statusText
    });
    throw new Error(`OpenRouter API error: ${error}`);
  }

  const result = await response.json();
  const content = result.choices?.[0]?.message?.content?.trim() || "";

  logger.info('OpenRouter API request successful', {
    model,
    contentLength: content.length,
    creativity
  });

  // Return exactly one answer
  return content;
}
